In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import random

In [2]:
mov = pickle.load(open('mov.pkl','rb'))
mov.head()

,adult,belongs_to_collection,budget,id,imdb_id,original_language,original_title,popularity,poster_path,production_companies,...,Crime,Romance,Fantasy,SciFi,Western,Mystery,Animation,Action,Comedy,War
0,0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000.0,862,tt0114709,en,Toy Story,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]",...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0,NaN,65000000.0,8844,tt0113497,en,Jumanji,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0.0,15602,tt0113228,en,Grumpier Old Men,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,NaN,16000000.0,31357,tt0114885,en,Waiting to Exhale,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,"{'id': 96871, 'name': 'Father of the Bride Col...",0.0,11862,tt0113041,en,Father of the Bride Part II,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [3]:
release_year = mov.release_date.apply(lambda x: int(x[:4])).rename("release_year")

In [4]:
mov = mov.join(release_year)

In [5]:
mov_most_budget = mov.sort_values(by=['budget'], ascending=False)
mov_most_popular = mov.sort_values(by=['popularity'], ascending=False)
mov_highest_rated = mov.sort_values(by=['vote_average'], ascending=False)
mov_most_voted = mov.sort_values(by=['vote_count'], ascending=False)
new_movies = mov_most_popular[mov_most_popular.release_year >= 2010]
old_movies = mov_most_popular[mov_most_popular.release_year <= 2000]
old_new_movies = mov_most_popular[(mov_most_popular.release_year > 2000) & (mov_most_popular.release_year <2010)]

In [6]:
new_movies.head()

,adult,belongs_to_collection,budget,id,imdb_id,original_language,original_title,popularity,poster_path,production_companies,...,Romance,Fantasy,SciFi,Western,Mystery,Animation,Action,Comedy,War,release_year
30700,0,"{'id': 86066, 'name': 'Despicable Me Collectio...",74000000.0,211672,tt2293640,en,Minions,547.488298,/q0R4crx2SehcEEQEkYObktdeFy.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2015
33356,0,"{'id': 468552, 'name': 'Wonder Woman Collectio...",149000000.0,297762,tt0451279,en,Wonder Woman,294.337037,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,"[{'name': 'Dune Entertainment', 'id': 444}, {'...",...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2017
42222,0,NaN,160000000.0,321612,tt2771200,en,Beauty and the Beast,287.253654,/tWqifoYuwLETmmasnGHO7xBjEtt.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017
43644,0,NaN,34000000.0,339403,tt3890160,en,Baby Driver,228.032744,/dN9LbVNNZFITwfaRjl4tmwGWkRg.jpg,"[{'name': 'Big Talk Productions', 'id': 443}, ...",...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2017
24455,0,NaN,165000000.0,177572,tt2245084,en,Big Hero 6,213.849907,/9gLu47Zw5ertuFTZaxXOvNfy78T.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,2014

In [7]:
def movies_displayed():
    mov1 = mov_highest_rated.head(100).sample(1)
    mov2 = mov_most_popular.head(100).sample(1)
    mov3 = mov_most_budget.head(100).sample(1)
    mov4 = mov_most_voted.head(100).sample(1)
    mov5 = new_movies.head(100).sample(1)
    mov6 = old_movies.head(100).sample(1)
    mov7 = old_new_movies.head(100).sample(1)
    
    displayed = [[mov1.original_title.values[0], mov1.id.values[0]], [mov2.original_title.values[0], mov2.id.values[0]], [mov3.original_title.values[0], mov3.id.values[0]], [mov4.original_title.values[0], mov4.id.values[0]], [mov5.original_title.values[0], mov5.id.values[0]], [mov6.original_title.values[0], mov6.id.values[0]], [mov7.original_title.values[0], mov7.id.values[0]]]
    
    return displayed

In [9]:
movies_displayed()

[['Witness for the Prosecution', '37257'],
 ['Guardians of the Galaxy', '118340'],
 ['Finding Dory', '127380'],
 ['The Dark Knight Rises', '49026'],
 ['Deadpool', '293660'],
 ['Planet of the Apes', '871'],
 ['Chicken Little', '9982']]

In [65]:
mov1 = mov_highest_rated.head(100).sample(1)

In [74]:
mov1.original_title.values[0]

'Dear Zachary: A Letter to a Son About His Father'

In [55]:
mov['original_title'].drop_duplicates().shape

(12193,)